name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Accept all Bubblewrap prompts
        run: |
          echo "N" | bubblewrap init \
            --manifest=https://pauliapp.netlify.app/manifest.json \
            --directory=./android

      - name: Build APK
        run: |
          cd android
          echo "" | bubblewrap build --skipPwaValidation

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PauliApp-APK
          path: android/*.apk
